### ISSUE TITLE
Implement support to deployment

### ISSUE THREAD

**Issue by nuxlli** [azukiapp/azk#10]

**Comment by gullitmiranda** [comment]
@nuxlli,

I believe this issue is partially implemented because the command `azk doctor` already exists, and shows part of the functionality defined here.

![image](https://cloud.githubusercontent.com/assets/2034678/7977013/2c109d7a-0a5b-11e5-8cdd-fad0cc8aa467.png)

**Comment by gullitmiranda** [comment]
closes by https://github.com/azukiapp/azk/pull/534
