### ISSUE TITLE
In Max OS X `bundler install` raise a error if the memory limit is reached

### ISSUE THREAD

**Issue by nuxlli** [azukiapp/azk#116]

**Comment by nuxlli** [comment]
According to the Docker specified https://github.com/docker/docker/blob/master/image/spec/v1.md#image-json-field-descriptions (more specifically the MemorySwap option), the containers are always executed unsupported the swap.

The solution could be in force for the Docker constigure the `azk` of containers with swap support.

**Comment by gullitmiranda** [comment]
@nuxlli, the docker documentation says:
> The operator can constrain the memory available to a container easily with docker run -m. If the host supports swap memory, then the -m memory setting can be larger than physical RAM.

In https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory

**Comment by gullitmiranda** [comment]
I managed to enable swap on the fly with a few commands. But you need to add the swap partition to `/etc/fstab` in [debian2docker](https://github.com/azukiapp/debian2docker).

In `azk vm ssh`:

1. Login as the root user
    
    ```sh
    $ sudo su
    ```

2. Type following command to create 512MB swap file (1024 * 512MB = 524288 block size):

    ```sh
    $ dd if=/dev/zero of=/swapfile1 bs=1024 count=524288 
    ```

3. Set up a Linux swap area:

    ```sh
    $ mkswap /mnt/sda1/swap2gb
    ```

4. Activate /swapfile1 swap space immediately:

    ```sh
    $ swapon /mnt/sda1/swap2gb
    ```

5. List active swaps:

    ```sh
    $ swapon -s
    ```

6. How do I verify swap is activated or not?
Simply use free command:

    ```sh
    $ free -m
    ```

7. Stress test:
    4 VMs each 256M for 30 seconds.

    ```sh
    docker run --rm --name stress-test jess/stress --vm 4 --vm-bytes 256M --timeout 30s
    ```
