### ISSUE TITLE
Improve the log of the download of the images on Docker Registry

### ISSUE THREAD

**Issue by nuxlli** [azukiapp/azk#119]
During the download process of the images to initialize systems, information of the download process of the layers that make up the image are displayed. But in some cases this information seem extremely confusing, reaching display progress bars superimposed.

Besides this problem, there is no global visibility of the donwload process. Can not identify the number of layers that are downloaded and which the total status of the download process.

**Comment by diegoleme** [comment]
I do not know if it's related to this issue, but ...
To me it appeared as 100% since the beginning
![azk_download](https://cloud.githubusercontent.com/assets/374857/7711803/6fafb31e-fe43-11e4-9d10-0cec2f41db38.jpg)

**Comment by saitodisse** [comment]
@diegoleme, this progress bar has some strange behaviours sometimes. :(
