### ISSUE TITLE
Error on azk start

### ISSUE THREAD

**Issue by reisfernanda** [azukiapp/azk#209]
Hi! I'm trying to run the example from http://docs.azk.io/pt-BR/index.html, but I get this error after running "azk start". This same error happens with example from https://github.com/azukiapp-samples/node-example.

azk: ↑ starting `azkdemo-master` system, 2 new instances...
azk: ✓ checking `node:0.10` image...
azk: ↻ provisioning `azkdemo-master` system...
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.10
npm ERR! path /azk/azkdemo-master/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/azk/azkdemo-master/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /azk/azkdemo-master/npm-debug.log

Thanks.

**Comment by lucasfais** [comment]
@reisfernanda sorry for the delay to answer this issue.

The sample repository you used is not valid anymore. We are sorry, again.

We have been refactoring our documentation and adding new examples. We plan to remove old examples very soon.

Follow the link to our new documentation (not official yet): http://azk-docs-stage.s3.amazonaws.com/pt-BR/getting-started/README.html
This is the new demo: https://github.com/azukiapp/azkdemo

We will keep this issue open until we deploy the new documentation.

**Comment by lucasfais** [comment]
Hey @reisfernanda, the official documentation link (http://docs.azk.io/) was update with the latest documentation version, in portuguese. The English version is coming in the next days. 

I will close this issue, but feel free to open new ones if you have any problems.
