### ISSUE TITLE
Changing the default domain

### ISSUE THREAD

**Issue by nuxlli** [azukiapp/azk#225]
We are using the `azk.dev` domain name in order to facilitate access of web application instances orchestrated with `azk`.

Unfortunately, despite `azk.dev` is working perfectly on Mac OS X and Linux (using the [libnss-resolver](https://github.com/azukiapp/libnss-resover)), it has  problems with the Google Chrome browser, especially in Linux.

The problems range from the `/` requirement at the end of uris (problem that also affects Mac OS X) to domain  resolution and a sporadic browser crash.

The problem seems to be related to `dev` not be a valid [TLD](http://en.wikipedia.org/wiki/Top-level_domain), as seen in [issue](https://code.google.com/p/chromium/issues/detail?id=30636#c38). The solution is to use a domain with a valid TLD, and, in this case, one that is "reserved" for Azuki. The suggestion is to replace the `*.azk.dev` by `*.dev.azk.io`.

**Comment by pkyeck** [comment]
Can I as a user change the default domain to something other than `*.dev.azk.io`?

**Comment by gullitmiranda** [comment]
@pkyeck, you can use the environment variable `AZK_BALANCER_HOST`. Right now, unless it's really necessary, we strongly do not recommend this practice.

eg:
```bash
$ export AZK_BALANCER_HOST=dev.example.com
$ azk agent start
$ azk start
```

Reminder: A command run in another shell context does not have the same hostname, unless you set it in your profile (`~/.zshrc` or `~/.bashrc`).

**Comment by pkyeck** [comment]
@gullitmiranda thanks for the quick reply. May I ask why you recommend not using this? Any sideeffects?

**Comment by gullitmiranda** [comment]
First because we do not estressamos this scenario. We have thought of improvements to be made in AZK that will make it more simple and functional.

Second, have reported problems in the first comment:

> The problem seems to be related to dev not be a valid TLD, as seen in issue. The solution is to use a domain with a valid TLD, and, in this case, one that is "reserved" for Azuki. The suggestion is to replace the *.azk.dev by *.dev.azk.io.

**Comment by pkyeck** [comment]
understood.
