### ISSUE TITLE
[Generators] Notify when the runtime version unidentified

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#237]
When the system version is not identified, the `azk` generator suggests the latest stable version of the language. e.g. `azukiapp/ruby:latest`. But, the user is not aware of why it was suggested this version and how he can change that.

So to improve usability, a notification will appears stating: 
- the version has not been identified
- `Azkfile.js` suggested another version
-  how you can make the change if you wish.

**Comment by nuxlli** [comment]
:+1:

**Comment by saitodisse** [comment]
merged on https://github.com/azukiapp/azk/pull/271
