### ISSUE TITLE
Fix cli options to show default values with numbers and other types

### ISSUE THREAD

**Issue by saitodisse** [azukiapp/azk#259]
When we execute a command `azk help` it does not show the "default" value for lines option:

![image](https://cloud.githubusercontent.com/assets/155953/6049474/0e980d92-ac9f-11e4-8bd4-70d9cd5bb6fa.png)

This requires a fix on `cli` azk's internal lib.

**Comment by nuxlli** [comment]
This fix involves a change in this code point,  to support the type `Number`: https://github.com/azukiapp/azk/blob/master/src%2Fcli%2Foption.js#L59-L71

But speaking specifically of `azk logs` the best would be to change the parse system to support "key words" that would be mapped to values ​​such as `all => 0` and make `0` the default value to display all lines.
