### ISSUE TITLE
[vm] invalid action `azk vm install`

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#260]
```sh
$ azk vm start
azk: virtual machine is not installed, try `azk vm install`.
$ azk vm install
azk: Invalid value: install in option action
```

**Comment by nuxlli** [comment]
You're right. Actually this command became "not supported" after this major change of https://github.com/azukiapp/azk/issues/113. In this amendment the virtual machine installation process can only be done during agent startup.

My suggestion is to keep the issue and we remove the support to `azk vm install`.
