### ISSUE TITLE
Add option `--rebuild` to `azk shell`

### ISSUE THREAD

**Issue by lucasfais** [azukiapp/azk#269]
When using a `Dockerfile` as a base image, I would like to have a `--rebuild` option in `azk shell` command, like `azk start --rebuild`.

**Comment by gregpardo** [comment]
Pretty sure this is in now. The option works for me

**Comment by gullitmiranda** [comment]
Fixed in #221 PR.

**Comment by philss** [comment]
I think this issue should be closed, like said in #221.

**Comment by gullitmiranda** [comment]
Are you sure @philss.
I'll close it. 
Thank you for identifying it.

**Comment by nuxlli** [comment]
Something is wrong,

PR #221 adds `--rebuild` to `start` and `restart`, not in `azk shell`, as can be seen here: https://github.com/azukiapp/azk/blob/9bc9bdccb3dee8852053a3c9ba572e809aec8784/src/cmds/shell.js#L151-L163

**Comment by philss** [comment]
@nuxlli sorry. I didn't notice that.

**Comment by nuxlli** [comment]
@philss no problem, none of us noticed this ;)

**Comment by gullitmiranda** [comment]
:sweat_smile:
