### ISSUE TITLE
Change Wercker badge to check only master branch

### ISSUE THREAD

**Issue by saitodisse** [azukiapp/azk#270]
This badge looks to all PR. Its too much:
[![wercker status](https://app.wercker.com/status/c771315d3c499dec99c49f49e8d1d84a/s "wercker status")](https://app.wercker.com/project/bykey/c771315d3c499dec99c49f49e8d1d84a)

We can change to only check master branch:
[![wercker status](https://app.wercker.com/status/c771315d3c499dec99c49f49e8d1d84a/s/master "wercker status")](https://app.wercker.com/project/bykey/c771315d3c499dec99c49f49e8d1d84a)

**Comment by heitortsergent** [comment]
Pull request #274
