### ISSUE TITLE
[npm] Replace `npm shrinkwrap` with `npm lockdown`

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#285]
## REFERENCES:

- https://www.npmjs.com/package/lockdown
- https://github.com/mozilla/npm-lockdown

**Comment by nuxlli** [comment]
After a few tests and a fix https://github.com/mozilla/npm-lockdown/pull/35, we verified that lockdown doesn't fix the problem we have of separating dev-dependencies from prod-dependencies
