### ISSUE TITLE
[Cli] Invalid permission to run azk in linux

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#289]
In linux `azk` is not allowed to be executed by other users.

Momentary solution:

```sh
$ sudo chmod o+x /usr/lib/azk/bin/*
```

**Comment by gregpardo** [comment]
Getting this behavior as well in Ubuntu 14.04. Note that on the website it says azk should not be run as sudo.

**Comment by gullitmiranda** [comment]
You are correct @gregpardo. We are working on bug fix and within moments will be available.
