### ISSUE TITLE
`azk start` command fails when `Azkfile.js` file is missing

### ISSUE THREAD

**Issue by marcusgadbem** [azukiapp/azk#304]
![image 2015-02-28 at 9 17 19 pm](https://cloud.githubusercontent.com/assets/254129/6428845/3d5994f4-bf8f-11e4-8ca0-5d64d27f48ca.png)

**Comment by nuxlli** [comment]
@marcusgadbem `azk` uses the same concept behind git where the manifest file, in case `Azkfile.js`, is look up in the same path level but once it is not found, the manifest file from parents path is used instead.

If you want to know which `Azkfile.js` is being used, just run `azk info`. In your case I believe that a file with a system example (which `azk init` suggests in case it does not recognize any structure) is being used.

Like this:

![screen shot 2015-03-01 at 12 12 42](https://cloud.githubusercontent.com/assets/8738/6431359/476d2d48-c00c-11e4-92bd-fc887b202670.png)

**Comment by marcusgadbem** [comment]
You are right. I found an missing `Azkfile.js` on its parents.
Thanks.
