### ISSUE TITLE
[Docs] Link to update the `azk v0.5.1` is broken

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#308]
It is necessary to make the change:

From: http://docs.azk.io/en/installation/upgrading.md#upgrading-from-azk--051
To: http://docs.azk.io/en/installation/upgrading.html#upgrading-from-azk--051

NOTE: in **PT-BR** is also broken.

**Comment by nuxlli** [comment]
Fixed with re-upload docs: http://docs.azk.io/en/installation/linux.html
