### ISSUE TITLE
`azk` does not start when disconnected from the network.

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#312]
![image](https://cloud.githubusercontent.com/assets/2034678/6561537/c75ad360-c670-11e4-9123-f0cf2405065c.png)

**Comment by heitortsergent** [comment]
@gullitmiranda I think you already have a solution, just saw that the folks from pow were having a similar issue here which boils down to /etc/resolver: basecamp/pow#104

**Comment by gullitmiranda** [comment]
yes @heitortsergent.
