### ISSUE TITLE
Mongoid cannot resolve .azk.io address when trying to connect from the host machine.

### ISSUE THREAD

**Issue by jturolla** [azukiapp/azk#319]
Mongoid with Rails fails to resolve the `mongodb.dev.azk.io` address to connect from the host machine when this address is in the configuration env of the app. 

The temporary fix was to resolve manually the address to `192.168.50.4` and use that.

**Comment by gullitmiranda** [comment]
hi @jturolla.
We believe that the pull request #322 will solve this problem. The next version will be available.
