### ISSUE TITLE
[cli] Missing --short description on azk help status

### ISSUE THREAD

**Issue by heitortsergent** [azukiapp/azk#324]
![image](https://cloud.githubusercontent.com/assets/446316/6672099/04cd5616-cbd8-11e4-8458-f91139ea271d.png)

**Comment by gullitmiranda** [comment]
This issue #324 fixed in #412 

![image](https://cloud.githubusercontent.com/assets/2034678/8962811/fe5a83d2-35f2-11e5-9f71-ca9b78dc7864.png)
