### ISSUE TITLE
Error "TypeError: Cannot read property '_left' of null" on azk agent start

### ISSUE THREAD

**Issue by synox** [azukiapp/azk#368]
in the vagrant image "phusion/ubuntu-14.04-amd64": 

	vagrant@ubuntu-14:~$ azk agent start
	azk: Wait, this process may take several minutes
	azk: Loading settings and checking dependencies.
	azk: Checking version...
	azk: Clearing 0 lost containers
	azk: Settings loaded successfully.
	azk: Agent is being started...
	azk: Trying to connect to docker (unix:///var/run/docker.sock) (1/10)...
	azk: Starting azk dns service...

	/usr/lib/azk/node_modules/is-online/node_modules/native-dns/node_modules/native-dns-cache/node_modules/binaryheap/binaryheap.js:68
	    if (!insert._left)
	               ^
	TypeError: Cannot read property '_left' of null
	    at [object Object].Heap.insert (/usr/lib/azk/node_modules/is-online/node_modules/native-dns/node_modules/native-dns-cache/node_modules/binaryheap/binaryheap.js:68:16)
	    at [object Object].MemoryStoreExpire.set (/usr/lib/azk/node_modules/is-online/node_modules/native-dns/node_modules/native-dns-cache/cache.js:78:17)
	    at /usr/lib/azk/node_modules/is-online/node_modules/native-dns/lib/platform.js:274:25
	    at Array.forEach (native)
	    at /usr/lib/azk/node_modules/is-online/node_modules/native-dns/lib/platform.js:273:26
	    at fs.js:272:14
	    at Object.oncomplete (fs.js:108:15)

	vagrant@ubuntu-14:~$ azk agent status
	azk: Agent is not running (try: `azk agent start`).

**Comment by gponsu** [comment]
Same error!

**Comment by nuxlli** [comment]
Hello @synox and @gponsu

During the v0.12.0 release tests, the error also occurred with us on DigitalOcean (Ubuntu 14.04). It's an intermittent error related to a problem with the lib https://www.npmjs.com/package/is-online.

I verified that the library is not updated on `azk`. We're going to update it and also add an error check to avoid an error with the lib to stop the agent from working, since verifying that the machine is online is not essential to `azk agent` working.

**Comment by slobo** [comment]
@gponsu the spaces in your ``sudo rm -rf`` might make someone destroy their system...

**Comment by saitodisse** [comment]
I will edit his comment @slobo, :P
very dangerous

**Comment by gponsu** [comment]
Excuse me, I think not had space, but it's true, it is a dangerous command, I have changed it :)

Thank you very much!
