### ISSUE TITLE
azk agent does not start

### ISSUE THREAD

**Issue by synox** [azukiapp/azk#369]
my setup: digitalocean with ubuntu 14.04 64bit

	ubuntu@ubuntu:~/azkdemo$ azk agent start --no-daemon
	azk: Wait, this process may take several minutes
	azk: Loading settings and checking dependencies.
	azk: Checking version...
	ubuntu@ubuntu:~/azkdemo$ azk agent status
	azk: Agent is not running (try: `azk agent start`).

	$ service docker status
	docker start/running, process 4058

any clue?

**Comment by synox** [comment]
after another reboot it works... maybe it needs a hint in the install docs?

**Comment by heitortsergent** [comment]
Hey @synox, glad it worked. We do have a note in the docs about rebooting, but it was an issue that somtimes happened when you run `azk start`, not `azk agent start`: http://docs.azk.io/en/getting-started/running-application.html

I'm going try to spin up a droplet on DigitalOcean and reproduce this. Thanks! :)

**Comment by nuxlli** [comment]
@synox, we've just launched a new azk version [`0.12.1`](https://github.com/azukiapp/azk/blob/master/CHANGELOG.md#v0121---2015-25-04) with the fix to your problem. Would you mind to test it, please?
