### ISSUE TITLE
[Agent] Ugly message when you are unable to identify the version

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#371]
With slow and unstable internet connection the `azk` was not able to check the version! 
![image](https://cloud.githubusercontent.com/assets/2034678/7299598/43bd2ce6-e9ad-11e4-9e8c-300ec15c5ce2.png)

For these cases believe that the ideal is to have the latest version already identified cached in order to display it instead to a bad message.

**Comment by saitodisse** [comment]
I'm resolving the https://github.com/azukiapp/azk/issues/368, so I will do this too

**Comment by gullitmiranda** [comment]
Good job @saitodisse.
