### ISSUE TITLE
[agent] azk agent does not stop

### ISSUE THREAD

**Issue by fearenales** [azukiapp/azk#372]
Running in an Ubuntu 12.04 box, with env ANALYTICS_DATA **unset**

When running `azk agent` in daemon mode, it doesn't stop with `azk agent stop`:

```bash
$ azk agent stop
azk: Agent is being stopped...
# after some time, it times out
azk: azk agent stop error (try `azk agent status`)
```
Checking processes, I still have `azk-agent` running in background.

**Comment by nuxlli** [comment]
Good point, @fearenales.

If anyone else is experiencing this issue, until we release a fix for that, you can kill azk agent (and its subprocesses) by running:

```shell
ps -ef | grep 'azk' | grep -v 'VirtualBox' | awk '{print $2}' | xargs kill -9
```
