### ISSUE TITLE
[cli] azk shell --mount option isn't working

### ISSUE THREAD

**Issue by fearenales** [azukiapp/azk#378]
I've tried to run:
```
azk shell pkg-ubuntu12-test --shell=/bin/bash --mount /tmp/azk-test:/azk/test
```

However, the /azk/test wasn't mounted inside the container.
I've also made a `docker inspect` in the container and the `/azk/test` folder isn't present as well:
```
...
"Volumes": {
        "/azk/azk": "/media/Data/home/felipe/workspace/azukiapp/azk",
        "/azk/data": "/media/Data/home/felipe/.azk/data/persistent_folders/362f1e298f/data-pkg-ubuntu12-test",
        "/var/lib/docker": "/media/Data/home/felipe/.azk/data/persistent_folders/362f1e298f/docker_files-pkg-ubuntu12-test"
    },
    "VolumesRW": {
        "/azk/azk": true,
        "/azk/data": true,
        "/var/lib/docker": true
    }
```

**Comment by nuxlli** [comment]
@fearenales, this a weird error once `azk shell` is parsing these options at:  https://github.com/azukiapp/azk/blob/master/src%2Fcmds%2Fshell.js#L51-L53.

A problem may be happening when merging options from command line with the ones in Azkfile.js when building parameters to pass over to Docker: https://github.com/azukiapp/azk/blob/master/src%2Fsystem%2Findex.js#L491-L528

**Comment by fearenales** [comment]
thanks @nuxlli. Quite precise :)
