### ISSUE TITLE
Review the places where we're using blocking IO

### ISSUE THREAD

**Issue by heitortsergent** [azukiapp/azk#383]
Even in some cases where you can not run anything without reading a file (such as in reading an Azkfile), we should not use blocking IO, as this can affect the exchange of `postal` messages, making the user experience slowness in `azk`'s cli  even when it's not the case.

We need to review all the code and check if there are alternative ways to not use blocking IO in places where we are using it.

**Comment by saitodisse** [comment]
`bluebird` lib has a good promisify implementation to give to `fs` promises. That's how I will start the solution for this issue.
