### ISSUE TITLE
Replace `progress` with `postal`

### ISSUE THREAD

**Issue by heitortsergent** [azukiapp/azk#385]
In the current architecture of `azk` we are using the "progress" system from the `Q` lib to "decouple" the interactions with the user from azk's internals.

An example is the agent boot process, which can do several things like: run the virtual machine, run containers and API services, all in classes and modules within the folder `src/agent`, which could be used by a graphic version of `azk`, and wouldn't show the progress status of these tasks on the command line.

The "progress" system of the Q lib has the following limitations:

- It is slow and blocking: once the function connected to progress is called, the program only continues after it has completed its execution;
- It's not a standard feature on the promise libs, thus we are stuck using the Q lib;
- Finally, there is no guarantee that messages from a group of promises come in the order they were sent to the progress system. This can lead to inconsistent outputs for the user, making it difficult to understand what happened;

To get away from the promises system, the best would be to use an approach based on events, or message box, in this case we can use the lib http://npmjs.com/package/postal, which among other things allows a different kind of "boundaries" which could facilitate the implementation of a graphic version of `azk`.

**Comment by saitodisse** [comment]
yep, progress is deprecated: https://github.com/petkaantonov/bluebird/issues/91
