### ISSUE TITLE
Replace Q for a better promises solution

### ISSUE THREAD

**Issue by heitortsergent** [azukiapp/azk#386]
Some benchmark tests show that the Q lib is not the best in performance when it comes to libraries that deal with the concept of promises.

The Bluebird lib has proven to be the best for this purpose, but we can also test the option of native ES6 promises, although this offers less features than the first two options.

In the case of native promises we would still need other libs to use features present in the other two libs. In particular: promisify and async with generators.

It is important to note that there is no point in replacing the Q lib inside `azk` if it is not done in the libs that are part of `azk` dependencies as well, after all the two libs would still have to be loaded.

- [x] Research if we're going to use ES6 or Bluebird promises 
- [x] Replaces `Q` direct calls with some wrapper functions to made easy to change promises lib on azk. Create `src/utils/promises` helper class
- [ ] Rewrite `src/utils/promises` with `bluebird`
- [ ] Replace Q with the one chosen above
- [ ] Replace the use of q-io to the version compatible with the choice above
- [ ] Benchmark

**Comment by saitodisse** [comment]
This is an up to date benchmark comparing all known promises libraries.
`bluebird` has almost the same performance that callbacks
https://github.com/petkaantonov/bluebird/tree/master/benchmark
