### ISSUE TITLE
User permission to be tracked is double checked by azk.Tracker and InsightKeenIO module

### ISSUE THREAD

**Issue by marcusgadbem** [azukiapp/azk#398]
There is a double check wether user has opted to be tracked or not in despite of the answer and both are not in sync.

A few things to observe:

* User permission is first checked at [azk/src/utils/tracker.js#L54](https://github.com/azukiapp/azk/blob/master/src%2Futils%2Ftracker.js#L54) and then in [insight-keen-io/lib/index.js#L107-L109](https://github.com/azukiapp/insight-keen-io/blob/master/lib/index.js#L107-L109)
* `azk.Tracker.savePermission()` stores user input inside own `azk.Meta` and do not share it with InsightKeenIO module
* InsightKeenIO has his [own store system](https://github.com/azukiapp/insight-keen-io/blob/master/lib/index.js#L49-L56) using `configstore` and defaults `optOut` to `false`

I think this can be fixed by changing `azk.Tracker.saveTrackerPermission(answer)` to share answer with InsightKeenIO by adding this line:

```javascript
this.insight.optOut = !answer;
```

The result will be:

```javascript
saveTrackerPermission(answer) {
	// we should negativate the answer because tracker 
	// works with 'optIn' and insight-keen-io works with 'optOut'
	this.insight.optOut = !answer;
    return azkMeta.set(this.ids_keys.permission, answer);
}
```

I'll make some tests to assure it and then make the PR.

**Comment by saitodisse** [comment]
Hello, @marcusgadbem. This verification is made by azk now. We are not using this insight feature anymore. I think that you can remove this verification from `insight-keen-io`.
