### ISSUE TITLE
System started with scalable: {default: 0, limit: 1} 

### ISSUE THREAD

**Issue by slobo** [azukiapp/azk#405]
Even though ``default:0``, ``azk start`` still starts the system.

**Comment by gullitmiranda** [comment]
@slobo, disable the system, only occurs when both (default and limit) are valued 0. I think this logic is not the ideal. We can discuss a little how it would be the most feasible way.

For technical purposes:

- the definition is being disabled is in https://github.com/azukiapp/azk/blob/master/src/system/index.js#L127-L129
- and the check to start a system is in https://github.com/azukiapp/azk/blob/master/src/cmds/start.js#L34-L40

**Comment by gullitmiranda** [comment]
### Source

In all suggestions: https://github.com/azukiapp/azk/tree/master/src/generator/suggestions

- [ ] Change default value for `scalable` to `1`
- [ ] Add comment to `scalable` property in Azkfile.js explaining why it defaults to `1`

### Docs

- [ ] Describe why user should use `scalable` only for features testing purposes (not performance)
