### ISSUE TITLE
[Tracker] `AZK_DISABLE_TRACKER=false` not working

### ISSUE THREAD

**Issue by gullitmiranda** [azukiapp/azk#408]
There is an error in checking tracker to be disabled. Like everything that comes in the environment variables is string, then 'false' is true.

https://github.com/azukiapp/azk/blob/master/src/utils/tracker.js#L153

#### Simple solution:

```javascript
  loadTrackerPermission() {
    if (!_.contains([false, 'false'], config('tracker:disable'))) {
      console.log('disabled');
      return false;
    }
    return azkMeta.get(this.ids_keys.permission);
  }
```

#### Best solution:

We can normalize the environment variables in the `envs`:
https://github.com/azukiapp/azk/blob/master/src/utils/index.js#L43-L47

```javascript
  envs(key, defaultValue = null) {
    var value = process.env[key];
    switch (value) {
      case 'undefined':
        value = undefined;
        break;
      case 'false':
        value = false;
        break;
      case 'true':
        value = true;
        break;
    }
    return value || (_.isFunction(defaultValue) ? defaultValue() : defaultValue);
  },
```

NOTE: correction of script above in the comment: https://github.com/azukiapp/azk/issues/408#issuecomment-103614876

**Comment by saitodisse** [comment]
:+1:

**Comment by nuxlli** [comment]
The second solution is is indeed better to, but has errors (including the original code):

If the value of the environment variable is `false` or `undefined` it will always fall in the value default, since `value ||` evaluates to false.

**Comment by gullitmiranda** [comment]
You're right, @nuxlli.

correction:
```javascript
envs(key, defaultValue = null) {
  var value = process.env[key];
  value = value || (_.isFunction(defaultValue) ? defaultValue() : defaultValue);
  switch (value) {
    case 'undefined':
      value = undefined;
      break;
    case 'null':
      value = null;
      break;
    case 'false':
      value = false;
      break;
    case 'true':
      value = true;
      break;
  }
  return value;
},
```

- [ ] Add tests
- [ ] Make implementation
