### ISSUE TITLE
azk : Depends: lxc-docker but it is not installable in apt-get install azk

### ISSUE THREAD

**Issue by joridos** [azukiapp/azk#410]
I try to install but received this error:

```bash
joridos@ceicom:~$ sudo apt-get install azk
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 azk : Depends: lxc-docker but it is not installable
E: Unable to correct problems, you have held broken packages.
```

My system information:
```bash
joridos@ceicom:~$ sudo docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): a78ce5c
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): a78ce5c

joridos@ceicom:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary OS
Description:	elementary OS Freya
Release:	0.3
Codename:	freya

joridos@ceicom:~$ uname -a
Linux ceicom 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by heitortsergent** [comment]
@joridos sorry about the error :(. @saitodisse do you know what might be the problem?

**Comment by gullitmiranda** [comment]
@joridos, your docker installation must be from `docker.io` and azk depends on `lxc-docker` which is the package maintained by Docker's team.
We recommend you to replace your current Docker installation with `lxc-docker` as shown in azk documentation.
However Elementary OS is based on Ubuntu we recommend using instructions for Ubuntu 12.04: http://docs.azk.io/en/installation/linux.html#ubuntu-precise-1204-lts-64-bit

**Comment by joridos** [comment]
Okay, I'm gonna try this way

**Comment by gullitmiranda** [comment]
@joridos worked for you?

**Comment by joridos** [comment]
WOW, I removed my current docker, and installed just the [lxc-docker](http://www.ubuntuupdates.org/pm/lxc-docker), and works. :smile: cheers.

**Comment by gullitmiranda** [comment]
Nice. So I will close this issue.
