### ISSUE TITLE
[docs] Better explanation at azkfilejs/mounts doc section

### ISSUE THREAD

**Issue by rafaelverger** [azukiapp/azk#411]
`azk version`: 0.12.1

First of all, it should tell that there are 2 ways to mount folders inside the container: `path` and `persistent`. And then it should explain how they work.

Will `path` keep container updated with host machine or it will only copy the files at the time that azk executes?

Another thing that should be changed is that when use `persistent('myfolder')` the content of this folder will be kept in `~/.azk/data/persistent_folders/#{manifest.id}/myfolder` instead of `~/.azk/data/persistent_folders/_SOME_ID_`

**Comment by heitortsergent** [comment]
@rafaelverger thanks for the feedback! 

We're gonna update this section with the information you suggested, and also adding a troubleshooting section on deleting persistent database information :)

**Comment by heitortsergent** [comment]
@rafaelverger would you mind telling us what you think of the changes we made? Is it better now? :dancer: 

http://docs.azk.io/en/reference/azkfilejs/mounts.html

**Comment by rafaelverger** [comment]
The `how it works` section is nice but :) Ah.. I think that this path isn't necessary: `/Users/heitorsergent/.azk/data/vm/azk-agent.vmdk.link`

And in the `example` section this is written:
```
* __persistent__: Persists the files within the container that are on the path
`/azk/bundler`. The files will usually be stored in the _host machine_ inside the folder
`~/.azk/data/persistent_folders/_SOME_ID_`.

mounts: {
   '/azk/bundler'          : persistent('bundler'),
}
```
I would replace `~/.azk/data/persistent_folders/_SOME_ID_` by `~/.azk/data/persistent_folders/#{manifest.id}/bundler`

**Comment by nuxlli** [comment]
Agreed,

But I'd complement with the info that, in Mac OS X, that folder is stored in a virtual disk (`~/.azk/data/vm/azk-agent.vmdk`) in the path `/azk/persistent_folders`. Plus, this disk is mounted in the path `/mnt/sda1` of the VM.

What do you think, @heitortsergent and @rafaelverger?

**Comment by rafaelverger** [comment]
Agreed @nuxlli :+1:
