### ISSUE TITLE
[docs] Improve landing page design

### ISSUE THREAD

**Issue by marcusgadbem** [azukiapp/azk#415]
Improve [http://docs.azk.io](http://docs.azk.io) landing page design and update section's logo as well.

This is the suggestion of the landing page: 

![image 2015-05-20 at 6 09 51 pm](https://cloud.githubusercontent.com/assets/254129/7736634/945dbc96-ff1b-11e4-9e41-032d4d518ba6.png)

**Comment by saitodisse** [comment]
I liked

**Comment by gullitmiranda** [comment]
:+1:
