### ISSUE TITLE
Fails to build a Dockerfile and mount

### ISSUE THREAD

**Issue by robsonpeixoto** [azukiapp/azk#419]
When I try to `start` a service using `dockerfile` and `mount` it mount the current directory as a subdirectory of the specified folder.

`OS`: Darwin updated.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
`azk version`: 0.13.0-beta1 and 0.12.1

Environment details: Virtualbox 4.3.28

Steps to Reproduce:
1. `git clone git@github.com:robsonpeixoto/simple-flask-azk.git`
2. `cd simple-flask-azk`
3. `azk start`

Actual Results:
```
azk:   Error in building `/Users/robinho/tmp/simple-flask-azk/Dockerfile`:
azk:     Step 0 : FROM python:2.7
azk:      ---> 2d0d013091cc
azk:     Step 1 : ADD . /code
azk:      ---> bc4c55a428de
azk:     Removing intermediate container 9c54e72e37b7
azk:     Step 2 : WORKDIR /code
azk:      ---> Running in 07c55e017c2d
azk:      ---> 91c7c0e7df1c
azk:     Removing intermediate container 07c55e017c2d
azk:     Step 3 : RUN ls
azk:      ---> Running in 662afd6bc625
azk:     Dockerfile
azk:     simple-flask-azk
azk:      ---> de4b4750d06f
azk:     Removing intermediate container 662afd6bc625
azk:     Step 4 : RUN pip install -r requirements.txt
azk:      ---> Running in 2d2bec42662c
azk:     Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
azk:     Removing intermediate container 2d2bec42662c
azk:     The command [/bin/sh -c pip install -r requirements.txt] returned a non-zero code: 1

azk: Due to the above error azk will stop all instances already running.

azk: System `web` not running
```
Additional info:

As can seed below, the `RUN ls` are showing the directory, not the directory contents.
```
azk:     Step 3 : RUN ls
azk:      ---> Running in 662afd6bc625
azk:     Dockerfile
azk:     simple-flask-azk
```

**Comment by robsonpeixoto** [comment]
I tests on version 0.13.0 and the error is the same

**Comment by gullitmiranda** [comment]
Robson Sorry, but this feature has not yet entered in this release. We will try to solve it and create a new version. Wait just a poquinho: D
