### ISSUE TITLE
Rsync process with 160%

### ISSUE THREAD

**Issue by dynaum** [azukiapp/azk#435]
After install rsync version I have this scenario on my machine:

![image](https://cloud.githubusercontent.com/assets/68991/7873402/33218e9a-0578-11e5-9e6c-55e559a762ac.png)

**Comment by gullitmiranda** [comment]
I put here the link to the conversation (in pt-BR) to contextualize:
https://gitter.im/azukiapp/azk/pt?at=5567a7cfbeed96397ea737be
