### ISSUE TITLE
Exit code not properly set on success

### ISSUE THREAD

**Issue by slobo** [azukiapp/azk#448]
When running ``azk start``, if some systems were already running it will exit with code ``3`` even if all the systems are now started. 

I'd expect it to return ``0`` if all required systems are now running, regardless of initial status of the system.

**Comment by slobo** [comment]
Similarly, ``azk stop`` returns wrong code when system is already stopped.
```
$ azk stop drupal; echo $?
azk: System `drupal` not running

 System  Inst.  Hostname/url              Instances-Ports 
 drupal  0      drupal.master.dev.azk.io  -               
3
```

**Comment by gullitmiranda** [comment]
:+1:
