### ISSUE TITLE
AZK agent not running

### ISSUE THREAD

**Issue by renanmpimentel** [azukiapp/azk#515]
If I remove all containers  by hand ``` docker rm $(docker ps -aq) ``` and type ``` azk start -vv ```, it does not ask if I want to run the agent, and when I enter ``` azk agent status ``` or ``` azk agent start ```, it says that the agent is running, see:

```
Linux (Ubuntu 15)
azk v0.14.6
Docker v1.8.1
```

``` bash
$ azk agent start 
azk: Agent is already running. 

$ docker ps -a 
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
76aeb16664ae        azukiapp/php-fpm:5.6   "/bin/sh -c '( compos"   44 seconds ago      Created                                 dev.azk.io_type.shell_mid.203a4d38df_sys.orcamentos_seq.1_shell.script_uid.0947d72050

```

**Comment by gullitmiranda** [comment]
As discussed in gitter (pt-BR), if you ever stop or even remove the dnsmasq or the load balancer services from azk, this will break name resolution. Thus, in those cases, you should restart azk agent.

If you'd like to clean your containers, I recommend you to check our gists and cheat sheets we've compiled: https://gist.github.com/gullitmiranda/d5e322cdf473a8dddf14#delete-stopped-containers
