### ISSUE TITLE
Possible to set user?

### ISSUE THREAD

**Issue by eproxus** [azukiapp/azk#517]
Is it possible to set (and create) the user that is used for provisioning and shell, similar to `RUN useradd myuser ...` and `USER myuser` directives in a Dockerfile?

**Comment by gullitmiranda** [comment]
It is possible to run shell commands in `provision`. It let you create a user but there is no such configuration you can set to tell which user to be used, similar to `USER` supported by Dockerfile.

We recommend you to create a Dockerfile and use it in you Azkfile.js.

You can find instructions here:  http://docs.azk.io/en/reference/azkfilejs/image.html#dockerfile

**Comment by eproxus** [comment]
Using `image: { dockerfile: "..." }` seems to ignore `provision`, is that true?

**Comment by gullitmiranda** [comment]
No. Provisioning is works the same way. But it is important to remember that the provision only runs automatically on the first run, after which it is necessary to "force" it.

- To force the provisioning run:

    ```shell
    $ azk start -R
    ```

- To force the build image (Dockerfile) run:

    ```shell
    $ azk start -BR
    ```

```Dockerfile
# Dockerfile
FROM azukiapp/erlang

RUN mkdir /home/myself && useradd myself && chown -R myself /home/myself
ENV HOME /home/myself

USER myself

CMD ["erl"]
```

```javascript
// Azkfile.js
systems({
  myApp: {
    // ...
    image: {"dockerfile": "./Dockerfile"},
    // ...
  },
  // ...
});
```

**Comment by eproxus** [comment]
This works. Adding `-R` and `-B` did the trick.

**Comment by gullitmiranda** [comment]
very nice.
