### ISSUE TITLE
Tab completion broken

### ISSUE THREAD

**Issue by eproxus** [azukiapp/azk#519]
### Description of the problem:

`OS`: OS X 10.10.5
`azk version`: `azk 0.14.6`

### Environment details (VirtualBox, DigitalOcean, etc.):
VirtualBox 5.0.3r102322

### Steps to Reproduce:
1. Sync a local directory:

    ```js
        mounts: {
            '/home/dev/#{manifest.dir}': sync("."), // path also doesn't work
        },
    ```
2. Put a cross-compiled Linux go binary in that directory (e.g. named `linux-binary`).
4. Try to tab complete that file by tying `lin<TAB>`

### Actual Results:
```
$ azk shell
dev@97ec9aef5322:~/backend$ ls
linux-binary
dev@97ec9aef5322:~/backend$ ./linazk: Error: HTTP code is 500 which indicates error: server error - Cannot destroy container 97ec9aef532243792acf6fc782e08ca63e1bb127b0b46ef6b0e872b2cd7077e4: Driver aufs failed to remove root filesystem 97ec9aef532243792acf6fc782e08ca63e1bb127b0b46ef6b0e872b2cd7077e4: rename /mnt/sda1/aufs/diff/97ec9aef532243792acf6fc782e08ca63e1bb127b0b46ef6b0e872b2cd7077e4 /mnt/sda1/aufs/diff/97ec9aef532243792acf6fc782e08ca63e1bb127b0b46ef6b0e872b2cd7077e4-removing: device or resource busy

azk:     at /usr/local/Cellar/azk/0.14.6/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:208:17
azk:     at getCause (/usr/local/Cellar/azk/0.14.6/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:236:7)
azk:     at [object Object].Modem.buildPayload (/usr/local/Cellar/azk/0.14.6/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:207:5)
azk:     at IncomingMessage.<anonymous> (/usr/local/Cellar/azk/0.14.6/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:183:14)
azk:     at IncomingMessage.emit (events.js:117:20)
azk:     at _stream_readable.js:944:16
azk:     at process._tickCallback (node.js:442:13)
```

### Expected Results:
```
$ ./linux-binary 
```

### Additional info:

Tab completion for folders and binaries in the image seems to work fine.

**Comment by gullitmiranda** [comment]
@eproxus 
1. What the script `linux-binary` do?
2. The image you are using this system is based on ubuntu?
3. The error occurred when you forced the closure of the shell (Ctrl + C or CMD + C)?

**Comment by eproxus** [comment]
1. It's a go binary that we have. I didn't even try to run it, just auto complete on the file name.
2. Yes, it's `eproxus/azukiapp-erlang` from Docker Hub.
3. No, the error occurs as soon as I press TAB after entering half of the file name, like so `./lin<TAB>`

**Comment by gullitmiranda** [comment]
I did a test to try to reproduce the error and did not get the same behavior. Here it functioned normally.
But I came up with another question. In his Azkfile.js there is the `shell: '/bin/bash',`?

Shell docs: http://docs.azk.io/en/reference/azkfilejs/shell.html

**Comment by eproxus** [comment]
Yes, that line is there.

**Comment by gullitmiranda** [comment]
@eproxus, unfortunately I do not know what's going on. But I add a task to try to reproduce the problem.

The problem persists or there only once?
If the problem persists, which would be the best way for me to play it?

**Comment by eproxus** [comment]
Hmm, I can't reproduce this with just a simple Ubuntu image and that same executable. Closing for now.

**Comment by gullitmiranda** [comment]
Less bad.
But what worries me here is that the azk broke.

**Comment by eproxus** [comment]
I'll update this issue if I see the problem again.

**Comment by gullitmiranda** [comment]
Thank you.
