### ISSUE TITLE
Undefined console output for image download progress

### ISSUE THREAD

**Issue by tuliomonteazul** [azukiapp/azk#531]
Running on Mac OS X 10.9.5
Azk version 0.15.0

After running `azk start -R -vv`, a lot of `undefined` values were printed incrementally. Probably has something to do with the image download progress.
Running the same command again didn't reproduce the problem.
Deleting the image with `adocker rmi -f` and running the same command, reproduced the problem.

Here is an image:
![screen shot 2015-10-01 at 19 37 33](https://cloud.githubusercontent.com/assets/791862/10235650/76706040-6874-11e5-850a-8048fdebf633.png)

My Azkfile has:  `image: {"dockerfile": "./docker/Dockerfile"},`
My Dockerfile is:
```
FROM nginx

COPY ./nginx.conf /etc/nginx/conf.d/agendor.conf
```

**Comment by saitodisse** [comment]
This error happens sometimes with me too. :(
Would be nice if I could easy simulate this to fix that.

**Comment by gullitmiranda** [comment]
@saitodisse , I believe that using the same Dockerfile the problem should be repeated?

**Comment by slobo** [comment]
This happens randomly to me too. I think it's usually first time we do azk start on a new machine, but could be wrong about that.

**Comment by saitodisse** [comment]
Yes @slobo, you are right. Every time when pulling new images this happens. 
To simulate that behaviour I did this, with a Dockerfile using `nodesource/node:0.12`:

```
azk stop; sudo service docker restart; docker rmi -f nodesource/node:0.12; adocker rmi -f $(adocker images -q -f dangling=true | tr '\r\n' ' '); azk start -Rvv;
```

I will try to fix this now
