### ISSUE TITLE
Remove bashisms from `shared/scripts/install.sh` script

### ISSUE THREAD

**Issue by fearenales** [azukiapp/azk#578]
The easiest way to install `azk` is by running `shared/scripts/install.sh` script, which can be accessible via http://azk.io/install.sh

In [azk docs](http://docs.azk.io/en/installation/#azk-express-installation), there are instructions to download the script and pipe it to `bash`, since the script is intended to be run using `bash` (you can see `#!/bin/bash` on its first line).

However, if the user pipes it to any other shell (`| sh`, as instance), it'll break due to syntax error.
To fix it, all [bashisms](http://mywiki.wooledge.org/Bashism) have to be removed from the installation script.

Plus, the documentation have to be updated in order to indicate the use of `sh` as the shell to be used.

**Comment by nuxlli** [comment]
Good proposal, but I think important to note a few things:

- `azk` requires `bash` for execution. The script `./bin/azk` have many `bashisms`;
- one of the most important steps of the script `./bin/azk` is the resolution step of `azk` path, which uses the variable `BASH_SOURCE`, so you must be careful in their modification;

**Comment by nuxlli** [comment]
A good reference on these issues is [that script](https://github.com/basho/node_package/blob/develop/priv/base/env.sh), used by the team http://basho.com in packaging their products based Erlang.

**Comment by fearenales** [comment]
@nuxlli Good points! I personally don't think it's bad to keep `bin/azk` using `bash`. That's pretty ok, once the user doesn't have to worry about it. Imho, `bin/azk` can be kept as it is.

My point is regard the installation script (`shared/scripts/install.sh`) is my point. It has to be piped into a shell. In `azk` docs, `bash` is used. But there are no guarantees that the user will pipe it into some other shell. And would be great if it worked, not a creepy syntax error be popped in screen, do you agree?

**Comment by nuxlli** [comment]
Yep, that makes sense.

For now I think we can focus on improving the `install.sh` script, but keep open the idea of making `./bin/azk` more agnostic.

**Comment by fearenales** [comment]
Cool! :)
