### ISSUE TITLE
Put all possible notation options and their description in docs.

### ISSUE THREAD

**Issue by hugobrilhante** [azukiapp/azk#579]
Put all possible notation options and their description. e.g.` #{system.name}` - System name.

**Comment by gullitmiranda** [comment]
The list of items that are expanded:
https://github.com/azukiapp/azk/blob/master/src/system/index.js#L538-L553

TODO:
- [ ] List of all itens
- [ ] Make friendly descriptions
- [ ] Make translation

**Comment by saitodisse** [comment]
I will do that one
