### ISSUE TITLE
install.sh error on Ubuntu 15.04 (Vivid)

### ISSUE THREAD

**Issue by zizuiZ** [azukiapp/azk#608]
```
[azk] Checking platform.......................................[ DONE ]
[azk]   Detected platform: linux, x64
[azk]   Detected distribution: ubuntu, 15.04
[azk] Enabling sudo...........................................[ WAIT ]
[azk]   echo sudo enabled
[azk] Enabling sudo...........................................[ DONE ]

[azk] [ERROR]   Unsupported Ubuntu version.
[azk] [ERROR]   Feel free to ask support for it by opening an issue at:
[azk] [ERROR]     https://github.com/azukiapp/azk/issues
[azk] [ERROR] Failed to install azk.
```

According to Requirements:
Distributions (tested): Ubuntu 12.04/14.04/15.04 and Fedora 20/21/22

**Comment by fearenales** [comment]
Thank you for your feedback @zizuiZ .

This information at our docs is incorrect.The supported versions of Ubuntu are: 12.04, 14.04 and 15.10.

**Comment by zizuiZ** [comment]
@fearenales,

Its impossible to use it on 15.04?

**Comment by fearenales** [comment]
@zizuiZ You can try install `azk` from source code. Just follow the instructions at http://docs.azk.io/en/installation/source-code.html.

Any further question, just let me know.

**Comment by zizuiZ** [comment]
Ok,

Thanks @fearenales.
