### ISSUE TITLE
Creating an image of a running container

### ISSUE THREAD

**Issue by jolic** [azukiapp/azk#612]
Hello,
thank you for this amazing tool. 

Is there any documentation that shows a step by step description how a custom image can be generated which can be used with azk?

I would like to take the node image, install some development stuff into it and use it with these changes.

Any help is appreciated!

Thank you.

**Comment by gullitmiranda** [comment]
hi @jolic 

This documentation helps you?
http://docs.azk.io/en/reference/azkfilejs/image.html

e.g. of extend the image: https://github.com/azukiapp/docker-elixir/#extend-image-with-dockerfile

```Dockerfile
# Dockerfile
FROM azukiapp/elixir:1.0

# install nodejs
# install postgresql-client
RUN  apk add --update nodejs postgresql-client \
  && rm -rf /var/cache/apk/* /var/tmp/* \

CMD ["iex"]
```

**Comment by jolic** [comment]
Thank you. I will try that.

**Comment by gullitmiranda** [comment]
good. I will close this issue. If you have problems or questions can open it again or you can call us on https://gitter.im/azukiapp/azk.
