### ISSUE TITLE
After initial azk deploy, subsequent deploys ask for password from git

### ISSUE THREAD

**Issue by patrickleet** [azukiapp/azk#626]
```shell
➜  elite git:(master) azk deploy
git@111.111.11.111's password:
```

From googling around it looks like the remote server needs access to git, which is a private repository.

Seems like it could be something like using SSH Agent Forwarding? https://developer.github.com/guides/using-ssh-agent-forwarding/

**Comment by gullitmiranda** [comment]
@patrickleet this problem is related to [azk-deploy](https://github.com/azukiapp/docker-deploy). You send this issue there?

https://github.com/azukiapp/docker-deploy/issues

**Comment by patrickleet** [comment]
Thanks, opened there.

https://github.com/azukiapp/docker-deploy/issues/18
