### ISSUE TITLE
Version 0.17.0 asking for docker-engine on Fedora

### ISSUE THREAD

**Issue by ReeSilva** [azukiapp/azk#643]
On Fedora 23 when trying to update Azk to 0.17.0 it fails by a broken dependency, docker-engine. But on Fedora the package has the name docker.

`OS`: Fedora 23
`azk version`: 0.17.0

Steps to Reproduce:
1. Install azk by repository
2. Try to update with `sudo dnf update`
3. Check the error of dependency with `sudo dnf update --best --allowerasing`

Additional info:
![captura de tela de 2016-03-30 00-27-14](https://cloud.githubusercontent.com/assets/3605032/14131076/3a3a8af6-f60e-11e5-8599-1f70dc7474ec.png)

**Comment by fearenales** [comment]
Thank you @ReeSilva for your feedback!
We're investigating it and a fix should be included in the next release.

**Comment by fearenales** [comment]
@ReeSilva , as you can check [here](https://github.com/docker/docker/blob/master/hack/install.sh#L450), the Docker package for Fedora is `docker-engine` in fact.

I believe that the issue that you are facing is that there's no repo with this package. So you have to manually add Docker's yum/dnf repo by creating the file `/etc/yum.repos.d/docker-main.repo` with the following content:

```
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/fedora/23
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```
To avoid this in the future, install `azk` by our [express instalation script](https://github.com/docker/docker/blob/master/hack/install.sh#L450):

```
$ curl -sSL http://azk.io/install.sh | sh
```

It will call Docker's installation script (which will create the repo file) and then install `azk`.

Please let me know if that worked for you :)

**Comment by ReeSilva** [comment]
Wow, I see now. I'm using the package provided by default on DNF. I'll try to configure the Docker repo and add a comment here.

Tkx.

**Comment by ReeSilva** [comment]
Worked like a charm. 

Tkx
