### ISSUE TITLE
Add Ubuntu 16.04 support

### ISSUE THREAD

**Issue by fearenales** [azukiapp/azk#656]
Ubuntu 16.04 is the new Ubuntu LTS version to be released on April 21st, 2016.

Both `azk` and [`libnss-resolver`](https://github.com/azukiapp/libnss-resolver/) have to be packed for this version.

**Comment by gullitmiranda** [comment]
instructions to make this improvement:
I think that the commits of the additions above are the great addition in the instructions.

1. libnss-resolver: : https://github.com/azukiapp/libnss-resolver/commit/00b56693dd20d9c4e60c56216a92b8a00c0aa955
2. azk: 
  - [ ] upgrade install express script: https://github.com/azukiapp/azk/commit/7330741d580bed923bd36e37a8414bea19f815a4
  - [ ] add systems `dind-ubuntu16` and `pkg-ubuntu16-test`
  - [ ] add instructions to build and publish package: 
    - https://github.com/azukiapp/azk/blob/master/src/libexec/package-tools/pack.sh#L308
    - https://github.com/azukiapp/azk/blob/master/src/libexec/package-tools/pack.sh#L319
  - [ ] add instructions to test: 
    - https://github.com/azukiapp/azk/blob/master/src/libexec/package-tools/test.sh#L8
    - https://github.com/azukiapp/azk/blob/master/src/libexec/package-tools/test.sh#L37-L40

after this any member of the team of the Azuki need to do the publication of the package.

**Comment by annielmenezes** [comment]
Hi people, has any prevision to launch package for Ubuntu 16.04? Tks.

**Comment by fearenales** [comment]
@annielmenezes It should be published within the next 2 weeks

**Comment by leandro-lugaresi** [comment]
Any new about this issue?

**Comment by aranwe** [comment]
Not sure if this is connected to this but when installing azuki I get 403 on the Xenial repo:
`[azk] Installing azk..........................................[ WAIT ]`
`[azk]   apt-key adv --keyserver keys.gnupg.net --recv-keys 022856F6D78159DF43B487D5C82CF0628592D2C9`
`[azk]   tee /etc/apt/sources.list.d/azuki.list`
`[azk]   apt-get update`
`W: The repository 'http://repo.azukiapp.com xenial Release' does not have a Release file.`
`E: Failed to fetch http://repo.azukiapp.com/dists/xenial/main/binary-amd64/Packages  403  Forbidden`
`E: Some index files failed to download. They have been ignored, or old ones used instead.`
`[azk] Installing azk..........................................[ FAIL ]`
