### ISSUE TITLE
Azk has issues with spaces inside your project path

### ISSUE THREAD

**Issue by m9dfukc** [azukiapp/azk#672]
**What are you trying do accomplish?**

Using `sync` Azk fails to work with paths that include spaces. Resulting in files not showing up inside your VM.

**Steps to reproduce the described behavior**

Make a new directory with spaces inside the path (f.e. ~/your project/hello) and then initialize a new azk project inside this directory. Exchange the `path` with the `sync` inside your `mount` command, then startup your system. Newley created files will not get synced to the right folder inside you virtual machine instead they will go into a folder looking like ".../your/hello". Using `path` this doesn't appear to be a issue.  

**Further info**

- running OSX 10.11.4 
- Virtual Box 5.0.12r104815
- azk version 0.18.0, build 8b9f66c

**Comment by fearenales** [comment]
thanks for reporting, @m9dfukc . I'll investigate it and let you know any news.
