### ISSUE TITLE
Can't install: Fail on make check_version Arch Linux

### ISSUE THREAD

**Issue by rodrigosaraiva** [azukiapp/azk#677]
I'm trying to install AZK on Arch Linux, and I get the error:

...
task: check_version
Error to run: /tmp/yaourt-tmp-rodrigo/aur-azk/src/azk-0.18.0/package/v0.18.0/usr/lib/azk/bin/azk version
Expect: azk 0.18.0
Output: azk 
make: *** [Makefile:166: check_version] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build azk.
==> Restart building azk ? [y/N]

The error occurs in both options to install, by wget or yaourt pure.

**Comment by gullitmiranda** [comment]
cc @fearenales

**Comment by fearenales** [comment]
@rodrigosaraiva Thanks for reporting.
I've just fixed the `PKGBUILD` file.

Please clean the `yaourt` tmp folder for `azk`:
```
rm -rf /tmp/yaourt-tmp-*/aur-azk
```

And then retry installing `azk`:
```
yaourt -S azk
```

Please let me know if this worked for you

**Comment by rodrigosaraiva** [comment]
Thanks @fearenales. The error was fixed.
