### ISSUE TITLE
Using .env in Azkfile.js

### ISSUE THREAD

**Issue by jonathanasquier** [azukiapp/azk#691]
Hi,
I have a .env on the root of my project folder with the Azkfile.js.
How can I use this variables inside the Azkfile.js without duplicating them plz?

thanks!

**Comment by gullitmiranda** [comment]
Try `${env.ENV_NAME}`.

Gullit Miranda

Em 1 de out de 2016 10:47, "Jonathan Asquier" notifications@github.com
escreveu:

**Comment by jonathanasquier** [comment]
Still getting

```
azk: List of deprecations:
azk: - `${}` is deprecated, use `#{env.ENV_NAME}` instead of `${env.ENV_NAME}` on `shooout-api.ports.http`

azk: ↑ starting `api` system, 1 new instances...
azk: ✓ checking `node:latest` image...
azk: ⎘ syncing files for `api` system...
azk: An error occurred. It will stop all instances already running. See details below.

azk: System `api` not running
azk: TypeError: Cannot read property 'protocol' of null
```

Same error with `#{env.ENV_NAME}` but without the deprecation

**Comment by m59peacemaker** [comment]
@jonathanasquier Did you figure this out? I'm having this problem also.

**Comment by jonathanasquier** [comment]
Nope, I ended up using docker-compose + volumes + pm2 for a fully
dockerized dev workflow. Works like à charm.

Le mar. 20 févr. 2018 à 02:09, Johnny Hauser <notifications@github.com> a
écrit :
